from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime

class ImageOptimized(BaseModel):
    id: str
    imageUrlSource: str
    imageUrlOptimized: str
    imageSizeKbSource: int
    imageSizeKbOptimized: int
    imageOptimizedComplete: bool
    imageOptimizedLastUpdated: str
    relID: int
    field: str
    relname: str

class Category(BaseModel):
    id: str
    label: str
    parentCategory: str
    slug: str
    publishedAt: str
    createdBy: str
    updatedBy: str
    createdAt: datetime
    updatedAt: datetime

class Tag(BaseModel):
    id: str
    label: str
    slug: str
    forceShow: bool
    publishedAt: str
    createdBy: int
    updatedBy: int
    createdAt: datetime
    updatedAt: datetime
    forceHide: bool
    isCarousel: bool

class Chat(BaseModel):
    id: str
    channelId: str
    channelName: str
    channelImage: str
    live: bool
    startTime: datetime
    endTime: datetime

class EventCreator(BaseModel):
    id: str
    creatorName: str
    creatorHandle: str
    creatorUrl: str
    creatorImage: str
    createdAt: datetime
    updatedAt: datetime

class Template(BaseModel):
    id: str
    eventTitle: str
    eventSlug: str
    eventImage: str
    marketTitle: str
    description: str
    resolutionSource: str
    negRisk: bool
    sortBy: str
    showMarketImages: bool
    seriesSlug: str
    outcomes: str

class Collection(BaseModel):
    id: str
    ticker: str
    slug: str
    title: str
    subtitle: str
    collectionType: str
    description: str
    tags: str
    image: str
    icon: str
    headerImage: str
    layout: str
    active: bool
    closed: bool
    archived: bool
    new: bool
    featured: bool
    restricted: bool
    isTemplate: bool
    templateVariables: str
    publishedAt: str
    createdBy: str
    updatedBy: str
    createdAt: datetime
    updatedAt: datetime
    commentsEnabled: bool
    imageOptimized: Optional[ImageOptimized]
    iconOptimized: Optional[ImageOptimized]
    headerImageOptimized: Optional[ImageOptimized]

class Series(BaseModel):
    id: str
    ticker: str
    slug: str
    title: str
    subtitle: str
    seriesType: str
    recurrence: str
    description: str
    image: str
    icon: str
    layout: str
    active: bool
    closed: bool
    archived: bool
    new: bool
    featured: bool
    restricted: bool
    isTemplate: bool
    templateVariables: bool
    publishedAt: str
    createdBy: str
    updatedBy: str
    createdAt: datetime
    updatedAt: datetime
    commentsEnabled: bool
    competitive: str
    volume24hr: int
    volume: int
    liquidity: int
    startDate: datetime
    pythTokenID: str
    cgAssetName: str
    score: int
    events: List[dict]
    collections: List[Collection]
    categories: List[Category]
    tags: List[Tag]
    commentCount: int
    chats: List[Chat]

class Event(BaseModel):
    id: str
    ticker: str
    slug: str
    title: str
    subtitle: str
    description: str
    resolutionSource: str
    startDate: datetime
    creationDate: datetime
    endDate: datetime
    image: str
    icon: str
    active: bool
    closed: bool
    archived: bool
    new: bool
    featured: bool
    restricted: bool
    liquidity: int
    volume: int
    openInterest: int
    sortBy: str
    category: str
    subcategory: str
    isTemplate: bool
    templateVariables: str
    published_at: str
    createdBy: str
    updatedBy: str
    createdAt: datetime
    updatedAt: datetime
    commentsEnabled: bool
    competitive: int
    volume24hr: int
    volume1wk: int
    volume1mo: int
    volume1yr: int
    featuredImage: str
    disqusThread: str
    parentEvent: str
    enableOrderBook: bool
    liquidityAmm: int
    liquidityClob: int
    negRisk: bool
    negRiskMarketID: str
    negRiskFeeBips: int
    commentCount: int
    imageOptimized: Optional[ImageOptimized]
    iconOptimized: Optional[ImageOptimized]
    featuredImageOptimized: Optional[ImageOptimized]
    subEvents: List[str]
    markets: List[dict]
    series: List[Series]
    categories: List[Category]
    collections: List[Collection]
    tags: List[Tag]
    cyom: bool
    closedTime: datetime
    showAllOutcomes: bool
    showMarketImages: bool
    automaticallyResolved: bool
    enableNegRisk: bool
    automaticallyActive: bool
    eventDate: str
    startTime: datetime
    eventWeek: int
    seriesSlug: str
    score: str
    elapsed: str
    period: str
    live: bool
    ended: bool
    finishedTimestamp: datetime
    gmpChartMode: str
    eventCreators: List[EventCreator]
    tweetCount: int
    chats: List[Chat]
    featuredOrder: int
    estimateValue: bool
    cantEstimate: bool
    estimatedValue: str
    templates: List[Template]
    spreadsMainLine: int
    totalsMainLine: int
    carouselMap: str
    pendingDeployment: bool
    deploying: bool
    deployingTimestamp: datetime
    scheduledDeploymentTimestamp: datetime
    gameStatus: str

class Market(BaseModel):
    id: str
    question: str
    conditionId: str
    slug: str
    twitterCardImage: str
    resolutionSource: str
    endDate: datetime
    category: str
    ammType: str
    liquidity: str
    sponsorName: str
    sponsorImage: str
    startDate: datetime
    xAxisValue: str
    yAxisValue: str
    denominationToken: str
    fee: str
    image: str
    icon: str
    lowerBound: str
    upperBound: str
    description: str
    outcomes: str
    outcomePrices: str
    volume: str
    active: bool
    marketType: str
    formatType: str
    lowerBoundDate: str
    upperBoundDate: str
    closed: bool
    marketMakerAddress: str
    createdBy: int
    updatedBy: int
    createdAt: datetime
    updatedAt: datetime
    closedTime: str
    wideFormat: bool
    new: bool
    mailchimpTag: str
    featured: bool
    archived: bool
    resolvedBy: str
    restricted: bool
    marketGroup: int
    groupItemTitle: str
    groupItemThreshold: str
    questionID: str
    umaEndDate: str
    enableOrderBook: bool
    orderPriceMinTickSize: int
    orderMinSize: int
    umaResolutionStatus: str
    curationOrder: int
    volumeNum: int
    liquidityNum: int
    endDateIso: str
    startDateIso: str
    umaEndDateIso: str
    hasReviewedDates: bool
    readyForCron: bool
    commentsEnabled: bool
    volume24hr: int
    volume1wk: int
    volume1mo: int
    volume1yr: int
    gameStartTime: str
    secondsDelay: int
    clobTokenIds: str
    disqusThread: str
    shortOutcomes: str
    teamAID: str
    teamBID: str
    umaBond: str
    umaReward: str
    fpmmLive: bool
    volume24hrAmm: int
    volume1wkAmm: int
    volume1moAmm: int
    volume1yrAmm: int
    volume24hrClob: int
    volume1wkClob: int
    volume1moClob: int
    volume1yrClob: int
    volumeAmm: int
    volumeClob: int
    liquidityAmm: int
    liquidityClob: int
    makerBaseFee: int
    takerBaseFee: int
    customLiveness: int
    acceptingOrders: bool
    notificationsEnabled: bool
    score: int
    imageOptimized: Optional[ImageOptimized]
    iconOptimized: Optional[ImageOptimized]
    events: List[Event]
    categories: List[Category]
    tags: List[Tag]
    creator: str
    ready: bool
    funded: bool
    pastSlugs: str
    readyTimestamp: datetime
    fundedTimestamp: datetime
    acceptingOrdersTimestamp: datetime
    competitive: int
    rewardsMinSize: int
    rewardsMaxSpread: int
    spread: int
    automaticallyResolved: bool
    oneDayPriceChange: int
    oneHourPriceChange: int
    oneWeekPriceChange: int
    oneMonthPriceChange: int
    oneYearPriceChange: int
    lastTradePrice: int
    bestBid: int
    bestAsk: int
    automaticallyActive: bool
    clearBookOnStart: bool
    chartColor: str
    seriesColor: str
    showGmpSeries: bool
    showGmpOutcome: bool
    manualActivation: bool
    negRiskOther: bool
    gameId: str
    groupItemRange: str
    sportsMarketType: str
    line: int
    umaResolutionStatuses: str
    pendingDeployment: bool
    deploying: bool
    deployingTimestamp: datetime
    scheduledDeploymentTimestamp: datetime
    rfqEnabled: bool
    eventStartTime: datetime