// This file is auto-generated. Do not edit manually.
// Run: pnpm generate-types
// Source: FastAPI OpenAPI schema

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autocomplete Markets */
        get: operations["autocomplete_markets_markets_autocomplete_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/search-slug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Markets Slug
         * @description Get a market by its slug from Polymarket Gamma API.
         *
         *     Official docs: https://docs.polymarket.com/api-reference/markets/get-market-by-slug
         */
        get: operations["search_markets_slug_markets_search_slug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Trades */
        get: operations["get_market_trades_markets_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/trades/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Trades Analytics */
        get: operations["get_market_trades_analytics_markets_trades_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Markets
         * @description Search for markets using Polymarket Gamma API.
         *     Returns events with their markets, filtered to only active markets.
         */
        get: operations["search_markets_markets_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/top-holders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Top Holders With Wallet Info Endpoint */
        get: operations["get_top_holders_with_wallet_info_endpoint_markets_top_holders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event By Id
         * @description Get an event by its ID from Polymarket Gamma API.
         *
         *     Official docs: https://docs.polymarket.com/api-reference/events/get-event-by-id
         */
        get: operations["get_event_by_id_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClobReward
         * @description Schema for a single CLOB reward configuration.
         */
        "ClobReward-Input": {
            /** Id */
            id: string;
            /** Conditionid */
            conditionId: string;
            /** Assetaddress */
            assetAddress: string;
            /** Rewardsamount */
            rewardsAmount: number | string;
            /** Rewardsdailyrate */
            rewardsDailyRate: number | string;
            /** Startdate */
            startDate: string;
            /** Enddate */
            endDate: string;
        };
        /**
         * ClobReward
         * @description Schema for a single CLOB reward configuration.
         */
        "ClobReward-Output": {
            /** Id */
            id: string;
            /** Conditionid */
            conditionId: string;
            /** Assetaddress */
            assetAddress: string;
            /** Rewardsamount */
            rewardsAmount: string;
            /** Rewardsdailyrate */
            rewardsDailyRate: string;
            /** Startdate */
            startDate: string;
            /** Enddate */
            endDate: string;
        };
        /** EventResponse */
        EventResponse: {
            event: components["schemas"]["EventSchema"];
        };
        /** EventSchema */
        EventSchema: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Closed */
            closed: boolean;
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** MarketAutocompleteItem */
        MarketAutocompleteItem: {
            /** Slug */
            slug: string;
            /** Question */
            question: string;
        };
        /** MarketSchema */
        "MarketSchema-Input": {
            /** Condition Id */
            condition_id: string;
            /** Question */
            question: string;
            /** Icon */
            icon: string;
            /** Outcomes */
            outcomes: string;
            /** Outcomeprices */
            outcomePrices: string;
            /** Slug */
            slug: string;
            /** Token1 */
            token1: string;
            /** Token2 */
            token2: string;
            /** Description */
            description: string;
            /** Liquidity */
            liquidity: number | string;
            /** Volume */
            volume: number | string;
            /** Volume24Hr */
            volume24hr: number | string;
            /** Volume1Wk */
            volume1wk: number | string;
            /** Volume1Mo */
            volume1mo: number | string;
            /** Volume1Yr */
            volume1yr: number | string;
            /** Negrisk */
            negRisk: boolean;
            /** Bestbid */
            bestBid: number | string;
            /** Bestask */
            bestAsk: number | string;
            /** Enddate */
            endDate: string;
            /** Events */
            events?: {
                [key: string]: unknown;
            }[] | null;
            /** Umareward */
            umaReward?: number | string | null;
            /** Clobrewards */
            clobRewards?: components["schemas"]["ClobReward-Input"][] | null;
            /** Rewardsminsize */
            rewardsMinSize?: number | string | null;
            /** Rewardsmaxspread */
            rewardsMaxSpread?: number | string | null;
            /** Holdingrewardsenabled */
            holdingRewardsEnabled?: boolean | null;
            /** Feesenabled */
            feesEnabled?: boolean | null;
        };
        /** MarketSchema */
        "MarketSchema-Output": {
            /** Condition Id */
            condition_id: string;
            /** Question */
            question: string;
            /** Icon */
            icon: string;
            /** Outcomes */
            outcomes: string;
            /** Outcomeprices */
            outcomePrices: string;
            /** Slug */
            slug: string;
            /** Token1 */
            token1: string;
            /** Token2 */
            token2: string;
            /** Description */
            description: string;
            /** Liquidity */
            liquidity: string;
            /** Volume */
            volume: string;
            /** Volume24Hr */
            volume24hr: string;
            /** Volume1Wk */
            volume1wk: string;
            /** Volume1Mo */
            volume1mo: string;
            /** Volume1Yr */
            volume1yr: string;
            /** Negrisk */
            negRisk: boolean;
            /** Bestbid */
            bestBid: string;
            /** Bestask */
            bestAsk: string;
            /** Enddate */
            endDate: string;
            /** Events */
            events?: {
                [key: string]: unknown;
            }[] | null;
            /** Umareward */
            umaReward?: string | null;
            /** Clobrewards */
            clobRewards?: components["schemas"]["ClobReward-Output"][] | null;
            /** Rewardsminsize */
            rewardsMinSize?: string | null;
            /** Rewardsmaxspread */
            rewardsMaxSpread?: string | null;
            /** Holdingrewardsenabled */
            holdingRewardsEnabled?: boolean | null;
            /** Feesenabled */
            feesEnabled?: boolean | null;
        };
        /** MarketSearchResponse */
        MarketSearchResponse: {
            market: components["schemas"]["MarketSchema-Output"];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** SearchEventItem */
        SearchEventItem: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Description */
            description?: string | null;
            /** Image */
            image?: string | null;
            /** Icon */
            icon?: string | null;
            /** Active */
            active: boolean;
            /** Closed */
            closed: boolean;
            /** Liquidity */
            liquidity?: number | null;
            /** Volume */
            volume?: number | null;
            /** Volume24Hr */
            volume24hr?: number | null;
            /** Markets */
            markets?: components["schemas"]["SearchMarketItem"][] | null;
        };
        /** SearchMarketItem */
        SearchMarketItem: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Conditionid */
            conditionId: string;
            /** Slug */
            slug: string;
            /** Category */
            category?: string | null;
            /** Liquidity */
            liquidity?: string | null;
            /** Volume */
            volume?: string | null;
            /** Outcomeprices */
            outcomePrices?: string | null;
            /** Outcomes */
            outcomes?: string | null;
            /** Active */
            active: boolean;
            /** Closed */
            closed: boolean;
            /** Icon */
            icon?: string | null;
            /** Image */
            image?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Events */
            events?: components["schemas"]["SearchEventItem"][] | null;
            /** Markets */
            markets?: components["schemas"]["SearchMarketItem"][] | null;
            /** Tags */
            tags?: {
                [key: string]: unknown;
            }[] | null;
            /** Profiles */
            profiles?: {
                [key: string]: unknown;
            }[] | null;
            /** Pagination */
            pagination?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TopHolderSchema
         * @description Polymarket holder schema enriched with wallet information and position data.
         */
        "TopHolderSchema-Input": {
            /** Proxywallet */
            proxyWallet: string;
            /** Bio */
            bio?: string | null;
            /** Asset */
            asset: string;
            /** Pseudonym */
            pseudonym?: string | null;
            /** Amount */
            amount: number;
            /** Displayusernamepublic */
            displayUsernamePublic: boolean;
            /** Outcomeindex */
            outcomeIndex: number;
            /** Name */
            name?: string | null;
            /** Profileimage */
            profileImage?: string | null;
            /** Profileimageoptimized */
            profileImageOptimized?: string | null;
            /** Walletcreatedat */
            walletCreatedAt?: string | null;
            /** Walletlasttransfer */
            walletLastTransfer?: string | null;
            /** Walletbalance */
            walletBalance?: number | string | null;
            /** Avgprice */
            avgPrice?: number | string | null;
            /** Realizedpnl */
            realizedPnl?: number | string | null;
            /** Totalbought */
            totalBought?: number | string | null;
        };
        /**
         * TopHolderSchema
         * @description Polymarket holder schema enriched with wallet information and position data.
         */
        "TopHolderSchema-Output": {
            /** Proxywallet */
            proxyWallet: string;
            /** Bio */
            bio?: string | null;
            /** Asset */
            asset: string;
            /** Pseudonym */
            pseudonym?: string | null;
            /** Amount */
            amount: number;
            /** Displayusernamepublic */
            displayUsernamePublic: boolean;
            /** Outcomeindex */
            outcomeIndex: number;
            /** Name */
            name?: string | null;
            /** Profileimage */
            profileImage?: string | null;
            /** Profileimageoptimized */
            profileImageOptimized?: string | null;
            /** Walletcreatedat */
            walletCreatedAt?: string | null;
            /** Walletlasttransfer */
            walletLastTransfer?: string | null;
            /** Walletbalance */
            walletBalance?: string | null;
            /** Avgprice */
            avgPrice?: string | null;
            /** Realizedpnl */
            realizedPnl?: string | null;
            /** Totalbought */
            totalBought?: string | null;
        };
        /** TradeSchema */
        TradeSchema: {
            /** Proxywallet */
            proxyWallet: string;
            /** Side */
            side: string;
            /** Asset */
            asset: string;
            /** Conditionid */
            conditionId: string;
            /** Size */
            size: number;
            /** Price */
            price: number;
            /** Timestamp */
            timestamp: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Icon */
            icon: string;
            /** Eventslug */
            eventSlug: string;
            /** Outcome */
            outcome: string;
            /** Outcomeindex */
            outcomeIndex: number;
            /** Name */
            name: string;
            /** Pseudonym */
            pseudonym: string;
            /** Bio */
            bio: string;
            /** Profileimage */
            profileImage: string;
            /** Profileimageoptimized */
            profileImageOptimized: string;
            /** Transactionhash */
            transactionHash: string;
        };
        /**
         * UserTradesGroup
         * @description Trades-based group per user for a single condition (market).
         */
        UserTradesGroup: {
            /** Proxywallet */
            proxyWallet: string;
            /** Name */
            name?: string | null;
            /** Pseudonym */
            pseudonym?: string | null;
            /** Profileimage */
            profileImage?: string | null;
            /** Totalvolume */
            totalVolume: number;
            /** Totalnotional */
            totalNotional: number;
            /** Totalusdvolume */
            totalUsdVolume: number;
            /** Totalholdings */
            totalHoldings: number;
            /** Trades */
            trades: components["schemas"]["TradeSchema"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    home__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    autocomplete_markets_markets_autocomplete_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketAutocompleteItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_markets_slug_markets_search_slug_get: {
        parameters: {
            query: {
                slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_trades_markets_trades_get: {
        parameters: {
            query: {
                condition_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_trades_analytics_markets_trades_analytics_get: {
        parameters: {
            query: {
                condition_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserTradesGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_markets_markets_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_holders_with_wallet_info_endpoint_markets_top_holders_get: {
        parameters: {
            query: {
                condition_id: string;
                token1: string;
                token2: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopHolderSchema-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_by_id_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}


// Clean type exports (no need to access via components["schemas"])
export type ClobRewardInput = components["schemas"]["ClobReward-Input"];
export type ClobReward = components["schemas"]["ClobReward-Output"];
export type EventResponse = components["schemas"]["EventResponse"];
export type EventSchema = components["schemas"]["EventSchema"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type MarketAutocompleteItem = components["schemas"]["MarketAutocompleteItem"];
export type MarketSchemaInput = components["schemas"]["MarketSchema-Input"];
export type MarketSchema = components["schemas"]["MarketSchema-Output"];
export type MarketSearchResponse = components["schemas"]["MarketSearchResponse"];
export type MessageResponse = components["schemas"]["MessageResponse"];
export type SearchEventItem = components["schemas"]["SearchEventItem"];
export type SearchMarketItem = components["schemas"]["SearchMarketItem"];
export type SearchResponse = components["schemas"]["SearchResponse"];
export type TopHolderSchemaInput = components["schemas"]["TopHolderSchema-Input"];
export type TopHolderSchema = components["schemas"]["TopHolderSchema-Output"];
export type TradeSchema = components["schemas"]["TradeSchema"];
export type UserTradesGroup = components["schemas"]["UserTradesGroup"];
export type ValidationError = components["schemas"]["ValidationError"];
