// This file is auto-generated. Do not edit manually.
// Run: pnpm generate-types
// Source: FastAPI OpenAPI schema

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/search-slug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market By Slug Endpoint
         * @description Get a market by its slug from Polymarket Gamma API.
         *
         *     Official docs: https://docs.polymarket.com/api-reference/markets/get-market-by-slug
         */
        get: operations["get_market_by_slug_endpoint_markets_search_slug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Trades Endpoint */
        get: operations["get_market_trades_endpoint_markets_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search Markets Endpoint
         * @description Search for markets using Polymarket Gamma API.
         *     Returns events with their markets, filtered to only active markets.
         */
        get: operations["get_search_markets_endpoint_markets_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/top-holders-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Top Holders Analysis Endpoint */
        get: operations["get_top_holders_analysis_endpoint_markets_top_holders_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event By Id Endpoint
         * @description Get an event by its ID from Polymarket Gamma API.
         *
         *     Official docs: https://docs.polymarket.com/api-reference/events/get-event-by-id
         */
        get: operations["get_event_by_id_endpoint_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClobReward
         * @description Schema for a single CLOB reward configuration.
         */
        ClobReward: {
            /** Id */
            id: string;
            /** Conditionid */
            conditionId: string;
            /** Assetaddress */
            assetAddress: string;
            /** Rewardsamount */
            rewardsAmount: number;
            /** Rewardsdailyrate */
            rewardsDailyRate: number;
            /** Startdate */
            startDate: string;
            /** Enddate */
            endDate: string;
        };
        /** Event */
        Event: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Closed */
            closed: boolean;
            /** Markets */
            markets?: components["schemas"]["Market"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** Market */
        Market: {
            /** Conditionid */
            conditionId: string;
            /** Question */
            question: string;
            /** Icon */
            icon: string;
            /** Image */
            image: string;
            /** Outcomes */
            outcomes: string;
            /** Outcomeprices */
            outcomePrices: string;
            /** Slug */
            slug: string;
            /** Token1 */
            token1: string;
            /** Token2 */
            token2: string;
            /** Description */
            description: string;
            /** Liquidity */
            liquidity: number;
            /** Volume */
            volume: number;
            /** Volume24Hr */
            volume24hr: number;
            /** Volume1Wk */
            volume1wk: number;
            /** Volume1Mo */
            volume1mo: number;
            /** Volume1Yr */
            volume1yr: number;
            /** Negrisk */
            negRisk: boolean;
            /** Bestbid */
            bestBid: number;
            /** Bestask */
            bestAsk: number;
            /** Enddate */
            endDate: string;
            /** Active */
            active: boolean;
            /** Closed */
            closed: boolean;
            /** Groupitemtitle */
            groupItemTitle: string;
            /** Events */
            events?: components["schemas"]["MarketEvent"][] | null;
            /** Umareward */
            umaReward?: number | null;
            /** Clobrewards */
            clobRewards?: components["schemas"]["ClobReward"][] | null;
            /** Rewardsminsize */
            rewardsMinSize?: number | null;
            /** Rewardsmaxspread */
            rewardsMaxSpread?: number | null;
            /** Holdingrewardsenabled */
            holdingRewardsEnabled?: boolean | null;
            /** Feesenabled */
            feesEnabled?: boolean | null;
        };
        /** MarketEvent */
        MarketEvent: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
        };
        /**
         * MessageResponse
         * @description Generic message response.
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * SearchEventItem
         * @description Lightweight event data from search API.
         */
        SearchEventItem: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Description */
            description?: string | null;
            /** Image */
            image?: string | null;
            /** Icon */
            icon?: string | null;
            /** Active */
            active: boolean;
            /** Closed */
            closed: boolean;
            /** Liquidity */
            liquidity?: number | null;
            /** Volume */
            volume?: number | null;
            /** Volume24Hr */
            volume24hr?: number | null;
            /** Markets */
            markets?: components["schemas"]["SearchMarketItem"][] | null;
        };
        /**
         * SearchMarketItem
         * @description Lightweight market data from search API.
         */
        SearchMarketItem: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Conditionid */
            conditionId: string;
            /** Slug */
            slug: string;
            /** Category */
            category?: string | null;
            /** Liquidity */
            liquidity?: string | null;
            /** Volume */
            volume?: string | null;
            /** Outcomeprices */
            outcomePrices?: string | null;
            /** Outcomes */
            outcomes?: string | null;
            /** Active */
            active: boolean;
            /** Closed */
            closed: boolean;
            /** Icon */
            icon?: string | null;
            /** Image */
            image?: string | null;
        };
        /**
         * SearchResponse
         * @description Response from Polymarket search API.
         */
        SearchResponse: {
            /** Events */
            events?: components["schemas"]["SearchEventItem"][] | null;
            /** Markets */
            markets?: components["schemas"]["SearchMarketItem"][] | null;
            /** Tags */
            tags?: {
                [key: string]: unknown;
            }[] | null;
            /** Profiles */
            profiles?: {
                [key: string]: unknown;
            }[] | null;
            /** Pagination */
            pagination?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TopHolderAnalysis
         * @description Polymarket holder enriched with wallet information and position data.
         */
        TopHolderAnalysis: {
            /** Proxywallet */
            proxyWallet: string;
            /** Bio */
            bio?: string | null;
            /** Asset */
            asset: string;
            /** Pseudonym */
            pseudonym?: string | null;
            /** Amount */
            amount: number;
            /** Displayusernamepublic */
            displayUsernamePublic: boolean;
            /** Outcomeindex */
            outcomeIndex: number;
            /** Name */
            name?: string | null;
            /** Profileimage */
            profileImage?: string | null;
            /** Profileimageoptimized */
            profileImageOptimized?: string | null;
            /** Walletcreatedat */
            walletCreatedAt?: string | null;
            /** Walletlasttransfer */
            walletLastTransfer?: string | null;
            /** Walletbalance */
            walletBalance?: number | null;
            /** Avgprice */
            avgPrice?: number | null;
            /** Realizedpnl */
            realizedPnl?: number | null;
            /** Totalbought */
            totalBought?: number | null;
        };
        /** Trade */
        Trade: {
            /** Proxywallet */
            proxyWallet: string;
            /** Side */
            side: string;
            /** Asset */
            asset: string;
            /** Conditionid */
            conditionId: string;
            /** Size */
            size: number;
            /** Price */
            price: number;
            /** Timestamp */
            timestamp: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Icon */
            icon: string;
            /** Eventslug */
            eventSlug: string;
            /** Outcome */
            outcome: string;
            /** Outcomeindex */
            outcomeIndex: number;
            /** Name */
            name: string;
            /** Pseudonym */
            pseudonym: string;
            /** Bio */
            bio: string;
            /** Profileimage */
            profileImage: string;
            /** Profileimageoptimized */
            profileImageOptimized: string;
            /** Transactionhash */
            transactionHash: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    home__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_market_by_slug_endpoint_markets_search_slug_get: {
        parameters: {
            query: {
                slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Market"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_trades_endpoint_markets_trades_get: {
        parameters: {
            query: {
                condition_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trade"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_markets_endpoint_markets_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_holders_analysis_endpoint_markets_top_holders_analysis_get: {
        parameters: {
            query: {
                condition_id: string;
                token1: string;
                token2: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopHolderAnalysis"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_by_id_endpoint_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}


// Clean type exports (no need to access via components["schemas"])
export type ClobReward = components["schemas"]["ClobReward"];
export type Event = components["schemas"]["Event"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type Market = components["schemas"]["Market"];
export type MarketEvent = components["schemas"]["MarketEvent"];
export type MessageResponse = components["schemas"]["MessageResponse"];
export type SearchEventItem = components["schemas"]["SearchEventItem"];
export type SearchMarketItem = components["schemas"]["SearchMarketItem"];
export type SearchResponse = components["schemas"]["SearchResponse"];
export type TopHolderAnalysis = components["schemas"]["TopHolderAnalysis"];
export type Trade = components["schemas"]["Trade"];
export type ValidationError = components["schemas"]["ValidationError"];
