// This file is auto-generated. Do not edit manually.
// Run: pnpm generate-types
// Source: FastAPI OpenAPI schema

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/top-movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Top Movers Endpoint
         * @description Get markets with highest absolute price delta (top movers).
         *     Returns markets sorted by absolute price change since last refresh.
         */
        get: operations["get_top_movers_endpoint_markets_top_movers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/search-slug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market By Slug Endpoint
         * @description Get a market by its slug from Polymarket Gamma API.
         *
         *     Official docs: https://docs.polymarket.com/api-reference/markets/get-market-by-slug
         */
        get: operations["get_market_by_slug_endpoint_markets_search_slug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Trades Endpoint */
        get: operations["get_market_trades_endpoint_markets_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search Markets Endpoint
         * @description Search for markets using Polymarket Gamma API.
         *     Returns events with their markets, filtered to only active markets.
         */
        get: operations["get_search_markets_endpoint_markets_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search Profiles Endpoint
         * @description Search for profiles using Polymarket Gamma API.
         */
        get: operations["get_search_profiles_endpoint_profiles_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/public-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Profile Endpoint
         * @description Get a public profile by address from Polymarket Gamma API.
         */
        get: operations["get_public_profile_endpoint_profiles_public_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/by-condition-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Markets By Condition Ids Endpoint
         * @description Get multiple markets by their condition IDs from Polymarket Gamma API.
         *
         *     Official docs: https://docs.polymarket.com/api-reference/markets/list-markets
         */
        get: operations["get_markets_by_condition_ids_endpoint_markets_by_condition_ids_get"];
        put?: never;
        /**
         * Post Markets By Condition Ids Endpoint
         * @description POST variant that accepts condition IDs in the JSON body.
         */
        post: operations["post_markets_by_condition_ids_endpoint_markets_by_condition_ids_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/top-holders-pnl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Top Holders Pnl Endpoint
         * @description Get PnL data for holders.
         *
         *     Accepts a list of TopHolder objects and returns them with PnL data (avgPrice, realizedPnl, totalBought).
         */
        post: operations["get_top_holders_pnl_endpoint_markets_top_holders_pnl_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/top-holders-wallet-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Top Holders Wallet Info Endpoint
         * @description Get wallet information for holders.
         *
         *     Accepts a list of TopHolder objects and returns them with wallet info (walletCreatedAt, walletLastTransfer, walletBalance).
         */
        post: operations["get_top_holders_wallet_info_endpoint_markets_top_holders_wallet_info_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event By Id Endpoint
         * @description Get an event by its ID from Polymarket Gamma API.
         *
         *     Official docs: https://docs.polymarket.com/api-reference/events/get-event-by-id
         */
        get: operations["get_event_by_id_endpoint_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/clarifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Clarifications Endpoint
         * @description Get all updates for a questionID and owner from the UMA CTF Adapter contract on-chain.
         *
         *     Calls getUpdates(bytes32 questionID, address owner) on contract 0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74.
         *     Results are cached in Redis for 24 hours.
         */
        get: operations["get_clarifications_endpoint_markets_clarifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_address}/pnl-with-markers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Pnl With Markers
         * @description Returns user PnL points and chart-aligned markers (swings and trade clusters).
         */
        get: operations["get_user_pnl_with_markers_users__user_address__pnl_with_markers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AncillaryDataUpdate
         * @description Ancillary data update from UMA CTF Adapter.
         */
        AncillaryDataUpdate: {
            /** Timestamp */
            timestamp: number;
            /** Text */
            text: string;
        };
        /** Body_post_markets_by_condition_ids_endpoint_markets_by_condition_ids_post */
        Body_post_markets_by_condition_ids_endpoint_markets_by_condition_ids_post: {
            /**
             * Condition Ids
             * @description JSON body: { "condition_ids": ["id1", ...] }
             */
            condition_ids: string[];
        };
        /**
         * ClobReward
         * @description Schema for a single CLOB reward configuration.
         */
        ClobReward: {
            /** Id */
            id: string;
            /** Conditionid */
            conditionId: string;
            /** Assetaddress */
            assetAddress: string;
            /** Rewardsamount */
            rewardsAmount: number;
            /** Rewardsdailyrate */
            rewardsDailyRate: number;
            /** Startdate */
            startDate: string;
            /** Enddate */
            endDate: string;
        };
        /** Event */
        Event: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Closed */
            closed: boolean;
            /** Markets */
            markets?: components["schemas"]["Market"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** MarkerMarketInfo */
        MarkerMarketInfo: {
            /** Title */
            title?: string | null;
            /** Outcome */
            outcome?: string | null;
            /** Tradescount */
            tradesCount?: number | null;
            /** Totalsize */
            totalSize?: number | null;
            /** Avgprice */
            avgPrice?: number | null;
            /** Notional */
            notional?: number | null;
            /** Side */
            side?: string | null;
        };
        /** MarkerTradeInfo */
        MarkerTradeInfo: {
            /** Hash */
            hash?: string | null;
            /** Title */
            title?: string | null;
            /** Outcome */
            outcome?: string | null;
            /** Side */
            side?: string | null;
            /** Size */
            size?: number | null;
            /** Price */
            price?: number | null;
            /** Notional */
            notional?: number | null;
            /** Timestamp */
            timestamp?: number | null;
        };
        /** Market */
        Market: {
            /** Conditionid */
            conditionId: string;
            /** Question */
            question: string;
            /** Questionid */
            questionId: string;
            /** Marketmakeraddress */
            marketMakerAddress: string;
            /** Submitted By */
            submitted_by: string;
            /** Icon */
            icon: string;
            /** Image */
            image: string;
            /** Outcomes */
            outcomes: string;
            /** Outcomeprices */
            outcomePrices: string;
            /** Slug */
            slug: string;
            /** Token1 */
            token1: string;
            /** Token2 */
            token2: string;
            /** Description */
            description: string;
            /** Liquidity */
            liquidity: number;
            /** Volume */
            volume: number;
            /** Volume24Hr */
            volume24hr: number;
            /** Volume1Wk */
            volume1wk: number;
            /** Volume1Mo */
            volume1mo: number;
            /** Volume1Yr */
            volume1yr: number;
            /** Negrisk */
            negRisk: boolean;
            /** Bestbid */
            bestBid: number;
            /** Bestask */
            bestAsk: number;
            /** Enddate */
            endDate: string;
            /** Active */
            active: boolean;
            /** Closed */
            closed: boolean;
            /** Groupitemtitle */
            groupItemTitle: string;
            /** Resolutionsource */
            resolutionSource: string;
            /** Events */
            events?: components["schemas"]["MarketEvent"][] | null;
            /** Umareward */
            umaReward?: number | null;
            /** Clobrewards */
            clobRewards?: components["schemas"]["ClobReward"][] | null;
            /** Rewardsminsize */
            rewardsMinSize?: number | null;
            /** Rewardsmaxspread */
            rewardsMaxSpread?: number | null;
            /** Holdingrewardsenabled */
            holdingRewardsEnabled?: boolean | null;
            /** Feesenabled */
            feesEnabled?: boolean | null;
        };
        /** MarketEvent */
        MarketEvent: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
        };
        /**
         * MessageResponse
         * @description Generic message response.
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * PnlMarker
         * @description Marker aligned to PnL chart timestamps.
         */
        PnlMarker: {
            /** T */
            t: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "swing" | "trade_cluster";
            /** Delta */
            delta?: number | null;
            /** Direction */
            direction?: ("up" | "down") | null;
            /** Severity */
            severity?: ("large" | "extreme") | null;
            /** Tradescount */
            tradesCount?: number | null;
            /** Notional */
            notional?: number | null;
            /** Markets */
            markets?: components["schemas"]["MarkerMarketInfo"][] | null;
            /** Trades */
            trades?: components["schemas"]["MarkerTradeInfo"][] | null;
        };
        /**
         * PnlPoint
         * @description Single PnL point for user PnL chart.
         */
        PnlPoint: {
            /** T */
            t: number;
            /** P */
            p: number;
        };
        /** PnlWithMarkersResponse */
        PnlWithMarkersResponse: {
            /** Points */
            points: components["schemas"]["PnlPoint"][];
            /** Markers */
            markers: components["schemas"]["PnlMarker"][];
        };
        /**
         * SearchEventItem
         * @description Lightweight event data from search API.
         */
        SearchEventItem: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Description */
            description?: string | null;
            /** Image */
            image?: string | null;
            /** Icon */
            icon?: string | null;
            /** Active */
            active: boolean;
            /** Closed */
            closed: boolean;
            /** Liquidity */
            liquidity?: number | null;
            /** Volume */
            volume?: number | null;
            /** Volume24Hr */
            volume24hr?: number | null;
            /** Markets */
            markets?: components["schemas"]["SearchMarketItem"][] | null;
        };
        /**
         * SearchMarketItem
         * @description Lightweight market data from search API.
         */
        SearchMarketItem: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Conditionid */
            conditionId: string;
            /** Slug */
            slug: string;
            /** Category */
            category?: string | null;
            /** Liquidity */
            liquidity?: string | null;
            /** Volume */
            volume?: string | null;
            /** Outcomeprices */
            outcomePrices?: string | null;
            /** Outcomes */
            outcomes?: string | null;
            /** Active */
            active: boolean;
            /** Closed */
            closed: boolean;
            /** Icon */
            icon?: string | null;
            /** Image */
            image?: string | null;
        };
        /** SearchProfileImageOptimized */
        SearchProfileImageOptimized: {
            /** Id */
            id: string;
            /** Imageurlsource */
            imageUrlSource: string;
            /** Imageurloptimized */
            imageUrlOptimized: string;
        };
        /** SearchProfileItem */
        SearchProfileItem: {
            /** Name */
            name: string;
            /** Proxywallet */
            proxyWallet: string;
            /** Pseudonym */
            pseudonym?: string | null;
            /** Displayusernamepublic */
            displayUsernamePublic: boolean;
            /** Createdat */
            createdAt?: string | null;
            /** Updatedat */
            updatedAt?: string | null;
            /** Profileimage */
            profileImage?: string | null;
            /** Bio */
            bio?: string | null;
            profileImageOptimized?: components["schemas"]["SearchProfileImageOptimized"] | null;
        };
        /**
         * SearchResponse
         * @description Response from Polymarket search API.
         */
        SearchResponse: {
            /** Events */
            events?: components["schemas"]["SearchEventItem"][] | null;
            /** Markets */
            markets?: components["schemas"]["SearchMarketItem"][] | null;
            /** Tags */
            tags?: {
                [key: string]: unknown;
            }[] | null;
            /** Profiles */
            profiles?: components["schemas"]["SearchProfileItem"][] | null;
            /** Pagination */
            pagination?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TopHolder
         * @description Single holder from Polymarket Data API.
         */
        TopHolder: {
            /** Proxywallet */
            proxyWallet: string;
            /** Bio */
            bio?: string | null;
            /** Asset */
            asset: string;
            /** Pseudonym */
            pseudonym?: string | null;
            /** Amount */
            amount: number;
            /** Displayusernamepublic */
            displayUsernamePublic: boolean;
            /** Outcomeindex */
            outcomeIndex: number;
            /** Name */
            name?: string | null;
            /** Profileimage */
            profileImage?: string | null;
            /** Profileimageoptimized */
            profileImageOptimized?: string | null;
        };
        /**
         * TopHolderPnl
         * @description TopHolder with PnL data only.
         */
        TopHolderPnl: {
            /** Proxywallet */
            proxyWallet: string;
            /** Bio */
            bio?: string | null;
            /** Asset */
            asset: string;
            /** Pseudonym */
            pseudonym?: string | null;
            /** Amount */
            amount: number;
            /** Displayusernamepublic */
            displayUsernamePublic: boolean;
            /** Outcomeindex */
            outcomeIndex: number;
            /** Name */
            name?: string | null;
            /** Profileimage */
            profileImage?: string | null;
            /** Profileimageoptimized */
            profileImageOptimized?: string | null;
            /** Avgprice */
            avgPrice?: number | null;
            /** Realizedpnl */
            realizedPnl?: number | null;
            /** Totalbought */
            totalBought?: number | null;
        };
        /**
         * TopHolderWalletInfo
         * @description TopHolder with wallet info only.
         */
        TopHolderWalletInfo: {
            /** Proxywallet */
            proxyWallet: string;
            /** Bio */
            bio?: string | null;
            /** Asset */
            asset: string;
            /** Pseudonym */
            pseudonym?: string | null;
            /** Amount */
            amount: number;
            /** Displayusernamepublic */
            displayUsernamePublic: boolean;
            /** Outcomeindex */
            outcomeIndex: number;
            /** Name */
            name?: string | null;
            /** Profileimage */
            profileImage?: string | null;
            /** Profileimageoptimized */
            profileImageOptimized?: string | null;
            /** Walletcreatedat */
            walletCreatedAt?: string | null;
            /** Walletlasttransfer */
            walletLastTransfer?: string | null;
            /** Walletbalance */
            walletBalance?: number | null;
        };
        /** TopHoldersPnlRequest */
        TopHoldersPnlRequest: {
            /** Holders */
            holders: components["schemas"]["TopHolder"][];
            /** Token1 */
            token1: string;
            /** Token2 */
            token2: string;
        };
        /** TopHoldersWalletInfoRequest */
        TopHoldersWalletInfoRequest: {
            /** Holders */
            holders: components["schemas"]["TopHolder"][];
        };
        /**
         * TopMover
         * @description Market with price movement data.
         */
        TopMover: {
            /** Clob Token Id */
            clob_token_id: string;
            /** Question */
            question: string;
            /** Slug */
            slug: string;
            /** Icon */
            icon: string;
            /** Last Price */
            last_price: number | null;
            /** Price Delta */
            price_delta: number | null;
            /** Fetched At */
            fetched_at: string;
        };
        /**
         * TopMoversResponse
         * @description Response for top movers endpoint.
         */
        TopMoversResponse: {
            /** Movers */
            movers: components["schemas"]["TopMover"][];
            /** Fetched At */
            fetched_at: string;
        };
        /** Trade */
        Trade: {
            /** Proxywallet */
            proxyWallet: string;
            /** Side */
            side: string;
            /** Asset */
            asset: string;
            /** Conditionid */
            conditionId: string;
            /** Size */
            size: number;
            /** Price */
            price: number;
            /** Timestamp */
            timestamp: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Icon */
            icon: string;
            /** Eventslug */
            eventSlug: string;
            /** Outcome */
            outcome: string;
            /** Outcomeindex */
            outcomeIndex: number;
            /** Name */
            name: string;
            /** Pseudonym */
            pseudonym: string;
            /** Bio */
            bio: string;
            /** Profileimage */
            profileImage: string;
            /** Profileimageoptimized */
            profileImageOptimized: string;
            /** Transactionhash */
            transactionHash: string;
        };
        /** UserProfileUser */
        UserProfileUser: {
            /** Id */
            id?: string | null;
            /** Creator */
            creator?: boolean | null;
            /** Mod */
            mod?: boolean | null;
        };
        /** UserPublicProfile */
        UserPublicProfile: {
            /** Id */
            id?: string | null;
            /** Createdat */
            createdAt?: string | null;
            /** Proxywallet */
            proxyWallet?: string | null;
            /** Profileimage */
            profileImage?: string | null;
            /** Displayusernamepublic */
            displayUsernamePublic?: boolean | null;
            /** Bio */
            bio?: string | null;
            /** Pseudonym */
            pseudonym?: string | null;
            /** Name */
            name?: string | null;
            /** Users */
            users?: components["schemas"]["UserProfileUser"][] | null;
            /** Xusername */
            xUsername?: string | null;
            /** Verifiedbadge */
            verifiedBadge?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    home__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_top_movers_endpoint_markets_top_movers_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMoversResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_by_slug_endpoint_markets_search_slug_get: {
        parameters: {
            query: {
                slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Market"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_trades_endpoint_markets_trades_get: {
        parameters: {
            query: {
                condition_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trade"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_markets_endpoint_markets_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_profiles_endpoint_profiles_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_profile_endpoint_profiles_public_profile_get: {
        parameters: {
            query: {
                address: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublicProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_markets_by_condition_ids_endpoint_markets_by_condition_ids_get: {
        parameters: {
            query: {
                /** @description Repeat the query param per ID */
                condition_ids: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Market"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_markets_by_condition_ids_endpoint_markets_by_condition_ids_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_post_markets_by_condition_ids_endpoint_markets_by_condition_ids_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Market"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_holders_pnl_endpoint_markets_top_holders_pnl_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopHoldersPnlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopHolderPnl"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_holders_wallet_info_endpoint_markets_top_holders_wallet_info_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopHoldersWalletInfoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopHolderWalletInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_by_id_endpoint_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clarifications_endpoint_markets_clarifications_get: {
        parameters: {
            query: {
                /** @description Question ID as hex string (bytes32) */
                question_id: string;
                /** @description Owner address */
                owner: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AncillaryDataUpdate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_pnl_with_markers_users__user_address__pnl_with_markers_get: {
        parameters: {
            query?: {
                interval?: string;
            };
            header?: never;
            path: {
                user_address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PnlWithMarkersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}


// Clean type exports (no need to access via components["schemas"])
export type AncillaryDataUpdate = components["schemas"]["AncillaryDataUpdate"];
export type Body_post_markets_by_condition_ids_endpoint_markets_by_condition_ids_post = components["schemas"]["Body_post_markets_by_condition_ids_endpoint_markets_by_condition_ids_post"];
export type ClobReward = components["schemas"]["ClobReward"];
export type Event = components["schemas"]["Event"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type MarkerMarketInfo = components["schemas"]["MarkerMarketInfo"];
export type MarkerTradeInfo = components["schemas"]["MarkerTradeInfo"];
export type Market = components["schemas"]["Market"];
export type MarketEvent = components["schemas"]["MarketEvent"];
export type MessageResponse = components["schemas"]["MessageResponse"];
export type PnlMarker = components["schemas"]["PnlMarker"];
export type PnlPoint = components["schemas"]["PnlPoint"];
export type PnlWithMarkersResponse = components["schemas"]["PnlWithMarkersResponse"];
export type SearchEventItem = components["schemas"]["SearchEventItem"];
export type SearchMarketItem = components["schemas"]["SearchMarketItem"];
export type SearchProfileImageOptimized = components["schemas"]["SearchProfileImageOptimized"];
export type SearchProfileItem = components["schemas"]["SearchProfileItem"];
export type SearchResponse = components["schemas"]["SearchResponse"];
export type TopHolder = components["schemas"]["TopHolder"];
export type TopHolderPnl = components["schemas"]["TopHolderPnl"];
export type TopHolderWalletInfo = components["schemas"]["TopHolderWalletInfo"];
export type TopHoldersPnlRequest = components["schemas"]["TopHoldersPnlRequest"];
export type TopHoldersWalletInfoRequest = components["schemas"]["TopHoldersWalletInfoRequest"];
export type TopMover = components["schemas"]["TopMover"];
export type TopMoversResponse = components["schemas"]["TopMoversResponse"];
export type Trade = components["schemas"]["Trade"];
export type UserProfileUser = components["schemas"]["UserProfileUser"];
export type UserPublicProfile = components["schemas"]["UserPublicProfile"];
export type ValidationError = components["schemas"]["ValidationError"];
